site_name: Web de Adrià Ferrando
theme:
  name: material
  palette:
    # Mode clar (per defecte)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    # Mode fosc automàtic
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
nav:
  - Inicio: index.md
  - Actividades:
      - "Ejercicio 1: Git y GitHub": ejercicio_1_introducci_n_a_git_y_github.md
      - "Ejercicio 2: Markdown": ejercicio_2_introducci_n_a_markdown.md
      - "Práctica 1: Ramas y Uniones": pr_ctica_1_git_ramas_y_uniones.md
      - "Práctica 2: Pull Request": pr_ctica_2_pull_request.md
      - "Práctica 3: MkDocs y GitHub Pages": pr_ctica_3_mkdocs_github_pages.md
      - "Práctica 4: Desplegamiento en GitHub Pages": pr_ctica_4_despliegue_github_pages
      - "Práctica 1: Instalación Servidor LEMP": pr_ctica_1_servidor_lemp
      - "Práctica 2: Servir Múltiples Dominios": pr_ctica_2_servir_m_ltiples_dominios
      - "Práctica 3: Web Segura": pr_ctica_3_web_segura_https
