site_name: Web de Adrià Ferrando
theme:
  name: material
  palette:
    # Mode clar (per defecte)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    # Mode fosc automàtic
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

